name: Test Branch

on:
  push:
    branches: [ main ]
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: 'go.mod'

      - uses: gotesttools/gotestfmt-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          args: --timeout=5m

      - name: Run tests
        run: GO_TEST_TAGS=-skip go test -coverprofile=coverage.out -race -json ./... | gotestfmt

      - uses: coverallsapp/github-action@v2
        with:
          file: coverage.out

